"""chage date

Revision ID: 542ab2cb91ca
Revises: 3ec524901ad9
Create Date: 2024-02-15 19:37:11.835127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542ab2cb91ca'
down_revision = '3ec524901ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
