"""def

Revision ID: e1477e187fbe
Revises: 7a75236e0618
Create Date: 2024-02-17 03:04:19.945804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1477e187fbe'
down_revision = '7a75236e0618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
